Proc macro expression feature gate has been renamed in nightly
    error[E0557]: feature has been removed
     --> src/main.rs:1:12
      |
    1 | #![feature(proc_macro_non_items)]
      |            ^^^^^^^^^^^^^^^^^^^^ feature has been removed
      |
      = note: subsumed by `#![feature(proc_macro_hygiene)]`